### ISSUE TITLE
ns-3 for Python > 3.7

### ISSUE THREAD

**Issue by lpirl** [osmhpi/python-wheels#2]
Where do know from that the ns-3 wheel works with Python 3.7 only (I guess it's "defined" here https://github.com/osmhpi/python-wheels/blob/17153893999db5c30f0c1c8a9e5b9fc1b806614b/ns-3/build.sh#L78).
What would have to be done to make the wheel compatible with Python > 3.7?

**Comment by rs22** [comment]
I think so. We should be able to create wheels for any other python >= 3.5 without any other modification.

The build process does not seem to implicitly depend on the Python version that is installed in the 'ubuntu-latest' runner (currently Ubuntu 18.04), which is 3.6.9 (among others): https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md

**Comment by lpirl** [comment]
The format seems to be defined in [PEP 425](https://www.python.org/dev/peps/pep-0425). Maybe we try `asset_path="$base/ns-$NS3_VERSION-py3-none-linux_x86_64.whl"` which should require:
* any Python3 implementation (cPython, PyPy, …)
* no specific Python ABI
* Linux x86_64 platform

This might be too relaxed (do we have ABI requirements?) but let's be optimistic and narrow the requirements down once problems occur.

**Comment by lpirl** [comment]
feel free to merge #3
